from tkinter import*
win = Tk()
l1=Label(win, text="Yellow Colour", bg="yellow", fg="black").pack()
l2=Label(win, text="Blue Colour", bg="blue", fg="black").pack()
l3=Label(win, text="Green Colour", bg="green", fg="black")
l3.pack(fill=X) # worked as parent widget to fill area
l4=Label(win, text="red Colour", bg="red", fg="black")
l4.pack(fill=X,padx=10)
l5=Label(win, text="orange Colour", bg="orange", fg="black")
l5.pack(fill=X,pady=10)
l6=Label(win, text="Pink Colour", bg="pink", fg="red")
l3.pack(ipadx=10)
l7=Label(win, text="Yellow Colour", bg="yellow", fg="red")
l7.pack(ipady=10)
l8=Label(win, text="Blue Colour", bg="blue", fg="white")
l8.pack(side=LEFT)
l9=Label(win, text="Green Colour", bg="green", fg="white")
l9.pack(side=LEFT)
mainloop()
